Yamblz-Iceberg/iceberg-app

- .eslintrc
- package-lock.json
> Переопределила количество пробелов на 4 для линта в propTypes

- README.md
> Обновил ридми 🐱

- src/components/elements/HashTag/HashTag.js
- src/components/elements/HashTag/HashTag.scss
- src/components/elements/HashTag/index.js
> Создал компонент 'HashTag'

- package-lock.json
- package.json
- src/components/blocks/tabs/tabs.js
- src/components/blocks/tabs/tabs.scss
- src/components/elements/tab-item/tab-item.js
- src/components/elements/tab-item/tab-item.scss
- src/components/pages/Home.js
- src/index.js
- src/reducers/index.js
- src/styles.scss
> Табы для ленты

- src/components/blocks/hash-tape/hash-tape.js
- src/components/blocks/hash-tape/hash-tape.scss
- src/components/blocks/hash-tape/index.js
- src/components/blocks/index.js
> Создал компонент хеш-ленты

- package.json
- src/index.js
Настроил статус бар. close #2.
Добавил обработчик на deviceready (пока закомментировано). close #20.
> StatusBar, обработчик на deviceready

- README.md
- config.xml
> Markdown tweaks

- webpack/development.config.js
> Добавила source-map в webpack.config

- src/components/blocks/collection-card/collection-card.js
- src/components/blocks/collection-card/collection-card.scss
> Добавил хэш-теги в компонент 'CollectionCard'

- src/index.html
> Поправила кодировку

- README.md
- package.json
> Issue #108

- src/components/blocks/tabs/tabs.scss
- src/components/pages/home/home.js
- src/components/pages/home/home.scss
- src/components/pages/home/index.js
- src/components/pages/index.js
- src/components/part/feed/feed.scss
- src/index.js
- src/styles.scss
> Добавил плавающую шапку + поправил структуру файлов у компонента home

- src/components/elements/floating-button/floating-button.js
- src/components/elements/floating-button/floating-button.scss
- src/components/elements/floating-button/index.js
- src/components/elements/index.js
- src/components/pages/home/home.js
> Добавил плавающую кнопку ➕

- src/components/pages/collection-detail/collection-detail.js
- src/reducers/collection.reducer.js
- src/reducers/index.js
- src/services/collection.service.js
> Написала сервис для забора информации о коллекции детально и связала с редаксом

- src/components/elements/floating-button/floating-button.js
> Добавил переход на создание новой коллекции

- config.xml
- package-lock.json
- package.json
- src/components/elements/icon/icon.js
> Починила загрузку иконок! 💪

- .eslintrc
- src/components/blocks/home-header/home-header.js
- src/components/blocks/index.js
- src/components/blocks/search-header/index.js
- src/components/blocks/search-header/search-header.js
- src/components/blocks/search-header/search-header.scss
- src/components/pages/index.js
- src/components/pages/search/index.js
- src/components/pages/search/search.js
- src/components/pages/search/search.scss
- src/components/parts/index.js
- src/components/parts/search-result/index.js
- src/components/parts/search-result/search-result.js
- src/components/parts/search-result/search-result.scss
- src/index.js
- src/reducers/index.js
- src/reducers/search.reducer.js
- src/styles.scss
> Issue #127 Страница поиска

- src/components/blocks/hash-tape/hash-tape.js
- src/components/parts/feed/feed.js
- src/reducers/feed.reducer.js
- src/services/feed.service.js
> Сделал рендер тегов в фиде

- src/components/blocks/index.js
- src/components/blocks/link-card/index.js
- src/components/blocks/link-card/link-card.js
- src/components/blocks/link-card/link-card.scss
- src/components/parts/feed/feed.js
> Issue #134 Компонент карточки-ссылки

- src/components/blocks/collection-detail-header/collection-detail-header.js
- src/components/blocks/collection-detail-header/collection-detail-header.scss
- src/components/blocks/template-card/template-card.js
- src/components/elements/hash-tag/hash-tag.scss
- src/components/pages/collection-detail/collection-detail.js
- src/components/parts/collection-detail-info/collection-detail-info.js
- src/components/parts/collection-detail-info/collection-detail-info.scss
- src/reducers/collection.reducer.js
> Issue #124

- src/components/blocks/collection-detail-header/collection-detail-header.js
- src/components/blocks/collection-detail-links/collection-detail-links.js
- src/components/blocks/collection-detail-links/collection-detail-links.scss
- src/components/blocks/collection-detail-links/index.js
- src/components/blocks/index.js
- src/components/blocks/link-card/link-card.js
- src/components/elements/button/button.scss
- src/components/pages/collection-detail/collection-detail.js
- src/components/pages/collection-detail/collection-detail.scss
- src/components/parts/collection-detail-info/collection-detail-info.js
- src/components/parts/collection-detail-info/collection-detail-info.scss
- src/reducers/collection.reducer.js
- src/variables.scss
> Issue #142

- src/components/blocks/index.js
- src/components/blocks/modal-error/index.js
- src/components/blocks/modal-error/modal-error.js
- src/components/blocks/modal-root/index.js
- src/components/blocks/modal-root/modal-root.js
- src/components/blocks/modal-template/index.js
- src/components/blocks/modal-template/modal-template.js
- src/components/blocks/modal-template/modal-template.scss
- src/components/blocks/search-header/search-header.js
- src/components/elements/button/button.js
- src/components/pages/search/search.js
- src/reducers/index.js
- src/reducers/modal.reducer.js
> Issue #140 Компонент модалки и доработки компонента кнопки

- src/components/parts/collection-detail-info/collection-detail-info.js
> Issue #149

- src/index.js
> Issue #146

- src/components/blocks/index.js
- src/components/blocks/toggle-text/index.js
- src/components/blocks/toggle-text/toggle-text.js
- src/components/blocks/toggle-text/toggle-text.scss
> Issue #152

- src/components/parts/collection-detail-info/collection-detail-info.js
- src/components/parts/collection-detail-info/collection-detail-info.scss
> Issue #148

- src/components/blocks/search-header/search-header.js
- src/components/elements/hash-tag/hash-tag.js
- src/components/elements/hash-tag/hash-tag.scss
Переход в поиск по тегу.
Возрат из поиска на предыдущую страницу, а не в ленту.
> Issue #155

- src/components/blocks/create-description-header/create-description-header.js
- src/components/blocks/create-description-header/create-description-header.scss
- src/components/blocks/create-description-header/index.js
- src/components/blocks/index.js
- src/components/blocks/limited-textarea/index.js
- src/components/blocks/limited-textarea/limited-textarea.js
- src/components/blocks/limited-textarea/limited-textarea.scss
- src/components/pages/create-description/create-description.js
- src/components/pages/create-description/create-description.scss
- src/components/pages/create-description/index.js
- src/components/pages/create-empty/create-empty.js
- src/components/pages/create-empty/create-empty.scss
- src/components/pages/index.js
- src/index.js
- src/reducers/create-collection.reducer.js
- src/reducers/index.js
> Issue #130

- src/components/blocks/collection-detail-links/collection-detail-links.js
- src/components/pages/collection-detail/collection-detail.js
- src/components/parts/collection-detail-info/collection-detail-info.js
- src/reducers/collection.reducer.js
> Issue #162

- config.xml
> Зафиксировала ориентацию экрана: только портретная

- src/styles.scss
> Issue #172

- src/components/blocks/create-link-header/create-link-header.js
- src/components/blocks/create-link-header/create-link-header.scss
- src/components/blocks/create-link-header/index.js
- src/components/blocks/index.js
- src/components/elements/button/button.js
- src/components/elements/button/button.scss
- src/components/pages/create-link/create-link.js
- src/components/pages/create-link/create-link.scss
- src/components/pages/create-link/index.js
- src/components/pages/index.js
- src/components/parts/collection-detail-info/collection-detail-info.js
- src/index.js
- src/reducers/index.js
- src/reducers/link.reducer.js
> Issue #163 Страница создания ссылки

- src/components/blocks/create-card/create-card.js
- src/components/blocks/create-empty-header/create-empty-header.js
- src/components/blocks/create-empty-header/create-empty-header.scss
- src/components/blocks/option/option.js
- src/components/elements/switch-button/switch-button.js
- src/components/pages/create-empty/create-empty.js
- src/reducers/create-collection.reducer.js
> Issue #161

- src/blocks/collection-detail/header/collection-detail-header.scss
- src/blocks/collection-detail/info/collection-detail-info.scss
> Поправила баг с шапкой после рефакторинга

- src/blocks/toggle-text/toggle-text.js
- src/blocks/toggle-text/toggle-text.scss
> Issue #175

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/collection-detail.scss
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/collection-detail/links/collection-detail-links.scss
> Добавила кнопку в коллекцию детально

- src/blocks/icon/icon.js
> Поправила баг с путем к спрайту

- src/blocks/switch-button/switch-button.scss
> Тенюшку сделала черной, а не желтой

- src/blocks/home/feed/home-feed.js
- src/blocks/home/home.js
- src/reducers/feed.reducer.js
- src/services/feed.service.js
> Сделал два разных запроса для страницы home ("моя лента" и "новое")

- src/blocks/button/button.js
- src/blocks/button/button.scss
> Перенесла основные стили в модификаторы, потом и background нужно

- src/blocks/collection-card/collection-card.js
- src/blocks/collection-card/collection-card.scss
- src/blocks/collection-detail/info/collection-detail-info.scss
- src/blocks/link-card/link-card.js
- src/blocks/link-card/link-card.scss
> Issue #233

- src/blocks/create-card/create-card.js
- src/blocks/create-card/create-card.scss
- src/blocks/create-hash-tag/create-hash-tag.scss
close #239 - Теперь рядом с хэштегами появляется кнопка и при клике на нее появляется новое поле для ввода хэштега
> Issue #239

- src/blocks/create-card/create-card.scss
- src/styles.scss
> Issue #225

- src/blocks/create-card/create-card.js
- src/blocks/create-empty/create-empty.js
- src/blocks/create-empty/header/create-empty-header.js
> Issue #226

- src/blocks/card-footer/card-footer.js
- src/blocks/card-footer/card-footer.scss
- src/blocks/card-footer/index.js
- src/blocks/collection-card/collection-card.js
- src/blocks/collection-detail/header/collection-detail-header.scss
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/collection-detail/info/collection-detail-info.scss
- src/blocks/create-card/create-card.js
- src/blocks/create-card/create-card.scss
- src/blocks/index.js
> Issue #241

- src/index.js
> chore(index.js): Improve debuggability.

- src/blocks/create-empty/header/create-empty-header.js
> Сделал добавление описания необязательным

- src/blocks/collection-detail/header/collection-detail-header.js
- src/blocks/collection-detail/header/collection-detail-header.scss
> Сделал плавающую шапку в collection-detail

- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/create-description/create-description.js
- src/blocks/create-description/header/create-description-header.js
- src/blocks/create-description/header/create-description-header.scss
- src/blocks/create-empty/create-empty.js
- src/blocks/create-link/add/create-link-add.js
- src/blocks/create-link/comment/create-link-comment.js
- src/blocks/create-link/comment/create-link-comment.scss
- src/blocks/create-link/create-link.js
- src/blocks/create-link/header/create-link-header.js
- src/blocks/create-link/header/create-link-header.scss
- src/blocks/create-link/load/create-link-load.js
- src/blocks/limited-textarea/limited-textarea.js
- src/blocks/link-card/link-card.js
- src/blocks/link-card/link-card.scss
- src/index.js
- src/reducers/create-collection.reducer.js
- src/reducers/link.reducer.js
- src/services/link.service.js
> Issue #245

- src/blocks/collection-card/collection-card.scss
- src/blocks/create-empty/create-empty.js
- src/blocks/create-link/create-link.js
- src/blocks/create-link/load/create-link-load.js
- src/index.js
> Issue #258

- src/blocks/collection-detail/collection-detail.js
- src/blocks/home/feed/home-feed.js
- src/blocks/search/header/search-header.js
- src/blocks/search/result/search-result.js
- src/reducers/collection.reducer.js
- src/reducers/feed.reducer.js
- src/reducers/search.reducer.js
- src/services/collection.service.js
- src/services/feed.service.js
- src/services/search.service.js
Может потом лучше хранить токен в куке?
> Добавил авторизацию для всех запросов

- src/blocks/create-hash-tag/create-hash-tag.js
close #264 - Добавлять теги при потере фокуса с поля ввода при создании коллекции
> Issue #264

- src/blocks/create-description/header/create-description-header.js
- src/blocks/create-description/header/create-description-header.scss
- src/blocks/limited-textarea/limited-textarea.js
> Issue #270

- src/blocks/create-link/add/create-link-add.js
- src/blocks/create-link/create-link.js
- src/blocks/modal-error/modal-error.js
- src/blocks/modal-template/modal-template.js
- src/reducers/modal.reducer.js
- src/utils/shared-functions.js
> Сделала модалку ошибки универсальной

- src/blocks/create-empty/create-empty.scss
> Изменил позиционирование у иконки редактирования

- src/blocks/create-link/add/create-link-add.js
- src/blocks/create-link/comment/create-link-comment.js
- src/blocks/create-link/header/create-link-header.js
- src/blocks/create-link/load/create-link-load.js
- src/blocks/link-card/link-card.js
- src/reducers/link.reducer.js
- src/services/link.service.js
> Сделать отображение комментария в карточках ссылки

- src/blocks/collection-detail/collection-detail.js
- src/blocks/create-link/add/create-link-add.scss
- src/blocks/link-card/link-card.js
- src/blocks/link-card/link-card.scss
- src/reducers/link.reducer.js
> Поправила заголовок ссылки, градиент ссылки, кликабельной кнопку внизу подборки, ограничила высоту страницы

- src/blocks/create-card/create-card.js
- src/blocks/create-card/create-card.scss
- src/blocks/create-hash-tag/create-hash-tag.scss
- src/blocks/link-card/link-card.scss
- src/blocks/user-info/user-info.scss
> Поправил незначительно ссылки и текст

- src/blocks/create-hash-tag/create-hash-tag.js
> Исправил баг при потерей фокусе с пустого поля ввода

- src/blocks/home/feed/home-feed.js
> Issue #296

- src/blocks/home/home.js
> Сбрасываю скролл при переходе по табам

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/info/collection-detail-info.js
> Поправила роут на добавление ссылки

- src/blocks/create-link/header/create-link-header.js
> Перенаправление после добавления в новое коллекции детально

- src/blocks/account-profile/account-profile.js
- src/blocks/account-profile/filter/account-profile-filter.js
- src/blocks/dropdown/item/dropdown-menu-item.scss
- src/reducers/bookmarks.reducer.js
- src/services/bookmarks.service.js
> Issue #316 Добавил фильтрацию ссылок "Добавленные мной"

- src/blocks/create-empty/header/create-empty-header.js
- src/blocks/create-empty/header/create-empty-header.scss
> Сообщение о требованиях при создании коллекции

- src/blocks/authorization/authorization.js
- src/blocks/authorization/authorization.scss
- src/blocks/authorization/index.js
- src/blocks/button/button.js
- src/blocks/index.js
- src/index.js
> Компонент страницы авторизации

- src/blocks/button/button.scss
- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/collection-detail.scss
- src/blocks/collection-detail/info/collection-detail-info.scss
> Правильное отображение кнопок на экране шириной 320px

- src/blocks/collection-card/collection-card.scss
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/collection-detail/info/collection-detail-info.scss
- src/blocks/hash-tag/hash-tag.scss
- src/blocks/hash-tape/hash-tape.js
- src/blocks/hash-tape/hash-tape.scss
- src/blocks/home/feed/home-feed.js
- src/blocks/home/feed/home-feed.scss
> Порефакторил стили, переделал hash-tape, сделал hash-tape в collection-detail

- src/blocks/create-card/create-card.js
- src/blocks/create-empty/header/create-empty-header.js
- src/blocks/home/feed/home-feed.js
- src/reducers/create-collection.reducer.js
- src/services/create-collection.service.js
Починил хэтеги:
- добавление
- нельзя ставить пробелы 
Починил добавление карточки.
> Issue #331 Починил добавление карточки

- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/hash-tag/hash-tag.js
- src/blocks/search/header/search-header.js
- src/blocks/search/result-item/search-result-item.js
- src/blocks/search/result/search-result.js
- src/services/search.service.js
- поиск по тегам
- открытие карточек в поиске
- возможность создания карточки при пустом результате
> Issue #226 Поиск

- src/blocks/account-profile/feed-item/account-profile-feed-item.js
- src/blocks/card-footer/card-footer.js
- src/blocks/collection-card/collection-card.js
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/toggle-text/toggle-text.js
- src/reducers/collection.reducer.js
> Issue #226 Доработки: переход из профиля в карточки, индикация подписки на карточке

- src/blocks/button/button.js
- src/blocks/button/button.scss
> Починил отображение кнопок в safari

- src/blocks/create-link/add/create-link-add.scss
- src/blocks/create-link/header/create-link-header.js
- src/blocks/create-link/header/create-link-header.scss
- src/blocks/user-info/user-info.scss
> Issue #342

- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/create-link/add/create-link-add.js
- src/blocks/create-link/comment/create-link-comment.js
- src/blocks/create-link/header/create-link-header.js
- src/blocks/create-link/header/create-link-header.scss
> Починил роуты при создании ссылки

- src/blocks/account-profile/account-profile.js
- src/blocks/account-profile/feed/account-profile-feed.js
- src/blocks/account-profile/feed/account-profile-feed.scss
- src/blocks/home/feed/home-feed.js
- src/blocks/index.js
- src/blocks/preloader/index.js
- src/blocks/preloader/preloader.js
- src/blocks/preloader/preloader.scss
- src/blocks/search/result/search-result.js
- src/reducers/bookmarks.reducer.js
- src/reducers/feed.reducer.js
- src/reducers/loader.reducer.js
> Issue #348

- src/blocks/account-profile/account-profile.js
- src/blocks/account-profile/feed-item/account-profile-feed-item.js
- src/blocks/account-profile/feed-item/account-profile-feed-item.scss
- src/blocks/dropdown/dropdown.scss
- src/blocks/dropdown/item/dropdown-menu-item.scss
- src/blocks/dropdown/menu/dropdown-menu.scss
- src/blocks/link-card/link-card.js
- доработал отображение dropdown
- скрываю favicon, если нет изображения
- переименовал Созданные другими в Сохраненные
> Issue #350  Профиль и favicon

- src/blocks/account-profile/account-profile.js
- src/blocks/account-profile/feed-item/account-profile-feed-item.scss
- src/blocks/account-profile/filter/account-profile-filter.js
- src/blocks/authorization/__modal/authorization__modal.js
- src/blocks/authorization/__modal/authorization__modal.scss
- src/blocks/authorization/authorization.js
- src/blocks/authorization/authorization.scss
- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/create-card/create-card.js
- src/blocks/create-empty/header/create-empty-header.js
- src/blocks/create-link/header/create-link-header.js
- src/blocks/create-link/load/create-link-load.js
- src/blocks/home/feed/home-feed.js
- src/blocks/home/home.js
- src/blocks/search/header/search-header.js
- src/blocks/search/search.js
- src/config.js
- src/reducers/authorization.reducer.js
- src/reducers/index.js
- src/reducers/loader.reducer.js
- src/services/authorization.service.js
- src/services/bookmarks.service.js
- src/services/collection.service.js
- src/services/create-collection.service.js
- src/services/feed.service.js
- src/services/link.service.js
- src/services/search.service.js
- src/services/user.service.js
- src/utils/shared-functions.js
> Issue #332

- src/blocks/home/home.js
- src/blocks/index.js
- src/blocks/middleware/index.js
- src/blocks/middleware/middleware.js
- src/blocks/middleware/middleware.scss
- src/index.js
- src/reducers/authorization.reducer.js
- src/services/authorization.service.js
> Сделала middleware

- src/blocks/create-description/create-description.js
> Уменьшил максимальное количество символов в описании до 300

- src/blocks/collection-card/collection-card.js
- src/blocks/home/feed/home-feed.js
- src/blocks/home/home.js
Перенес обработку длинного заголовка из карточки в формирование ленты.
> Issue #373 Поправил медленную загрузку ленты

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/collection-detail.scss
- src/blocks/collection-detail/header/collection-detail-header.js
- src/blocks/collection-detail/header/collection-detail-header.scss
- src/blocks/search/result/search-result.js
- убрал таб новое в карточке
- изменил текст выдачи в профиле
- сдвинул кнопку домой в карточке
- сделал отступ у кнопки Добавить ссылку
> Визуальные изменения на клиенте

- src/blocks/create-link/comment/create-link-comment.js
- src/blocks/create-link/header/create-link-header.js
- src/blocks/create-link/load/create-link-load.js
- src/blocks/create-link/load/create-link-load.scss
- src/blocks/link-card/link-card.js
- src/blocks/link-card/link-card.scss
- src/reducers/link.reducer.js
- src/reducers/loader.reducer.js
> Доработал экран загрузки ссылки и компонент ссылки

- src/blocks/button/button.scss
- src/blocks/collection-detail/collection-detail.scss
- src/blocks/collection-detail/header/collection-detail-header.js
- src/blocks/collection-detail/header/collection-detail-header.scss
- src/blocks/context-menu/__item/context-menu__item.js
- src/blocks/context-menu/__item/context-menu__item.scss
- src/blocks/context-menu/context-menu.js
- src/blocks/context-menu/context-menu.scss
- src/blocks/context-menu/index.js
- src/blocks/index.js
Контекстное меню в карточке коллекций.
> Issue #236 Компонент контекстого меню

- src/blocks/create-hash-tag/create-hash-tag.scss
> Поправила баг, когда placeholeder тега не влезает

- config.xml
- package.json
> Название проекта нормальным сделала

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/header/collection-detail-header.js
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/create-link/load/create-link-load.js
> Поправила баг с переходом в добавление ссылки и возвратом назад

- src/blocks/home/feed/home-feed.scss
> Отступ снизу фида увеличила

- src/blocks/create-link/header/create-link-header.js
- src/reducers/link.reducer.js
- src/services/link.service.js
- Удаляем недосозданную ссылку из бд.
> Роут на удаление ссылки.

- src/blocks/collection-card/collection-card.js
- src/blocks/collection-detail/collection-detail.js
- src/blocks/hash-tag/hash-tag.js
- src/blocks/hash-tape/hash-tape.js
- src/reducers/onboarding.reducer.js
- src/services/onboarding.service.js
- src/services/personal-tags.service.js
> Отправка personal tags при клике по тегам

- src/blocks/home/header/home-header.js
- src/blocks/link-card/link-card.js
- src/blocks/user-info/user-info.js
> Убрал упоминание о рейтинге и "молнию"

- src/blocks/card-footer/card-footer.js
- src/blocks/collection-card/collection-card.js
- src/blocks/context-menu/context-menu.scss
- src/blocks/index.js
- src/blocks/user-profile/__header/user-profile__header.js
- src/blocks/user-profile/__header/user-profile__header.scss
- src/blocks/user-profile/index.js
- src/blocks/user-profile/user-profile.js
- src/blocks/user-profile/user-profile.scss
- src/index.js
- src/reducers/another-user.reducer.js
- src/reducers/index.js
- src/services/another-user.service.js
Страница просмотра профиля другого пользователя
close #455
> Заготовки для просмотра другого пользователя

- src/blocks/account-profile/account-profile.js
- src/blocks/account-profile/feed-item/account-profile-feed-item.js
- src/blocks/account-profile/filter/account-profile-filter.js
- src/blocks/card-footer/card-footer.js
- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/collection-detail/links/collection-detail-links.js
- src/blocks/link-card/link-card.js
- src/reducers/another-user.reducer.js
- src/reducers/bookmarks.reducer.js
- src/reducers/collection.reducer.js
- src/reducers/link.reducer.js
- src/services/another-user.service.js
- src/services/bookmarks.service.js
- src/services/collection.service.js
- src/services/link.service.js
и другие не менее интересные доработки
> Issue #465 При открытии ссылки, она помечается как прочитанная

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/collection-detail.scss
- src/blocks/collection-detail/links/collection-detail-links.js
> Лоадер в коллекции детально, когда данные еще не получены

- src/blocks/card-footer/card-footer.js
- src/blocks/collection-detail/links/collection-detail-links.js
- src/blocks/link-card/link-card.js
> Проверка на авторизованность при клике на лайк и подписку ссылки

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/header/collection-detail-header.js
- src/blocks/create-empty/create-empty.js
- src/blocks/create-empty/header/create-empty-header.js
- src/blocks/creating-successfully/creating-successfully.js
- src/blocks/creating-successfully/header/creating-successfully-header.js
- src/blocks/home/feed/home-feed.js
- src/reducers/collection.reducer.js
- src/reducers/create-collection.reducer.js
+ очистка стейта после ухода из карточки
> Issue #456 Создание закрытых подборок

- src/blocks/search/result/search-result.js
> Вывожу нужный текст на экран поиска без запроса

- src/blocks/create-card/create-card.js
> При помещении тегов в 'state' делаю 'reverse'

- src/utils/shared-functions.js
> Изменил неправильное условие

- src/blocks/collection-detail/collection-detail.js
- src/blocks/toggle-text/toggle-text.js
- src/blocks/toggle-text/toggle-text.scss
> Баг с компонентом разворачивания описания

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/header/collection-detail-header.js
- src/blocks/collection-detail/links/collection-detail-links.js
- src/blocks/context-menu/__item/context-menu__item.js
- src/blocks/context-menu/__item/context-menu__item.scss
- src/blocks/context-menu/context-menu.js
- src/blocks/context-menu/context-menu.scss
- src/blocks/link-card/link-card.js
- src/blocks/link-card/link-card.scss
- src/reducers/collection.reducer.js
- src/services/collection.service.js
Доработки по контекстному меню и открытию ссылки - перенес метод и упростил проверку.
> Issue #480 Возможность удаление ссылки и коллекции у твоих записей

- package-lock.json
- src/blocks/avatar/avatar.js
- src/blocks/avatar/avatar.scss
> МедведЯ поправила 🐻

- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/links/collection-detail-links.js
> Сделала сброс скролла при переходе в колекцию детально

- src/blocks/tabs/tabs.js
- src/blocks/tabs/tabs.scss
close #408 Сделал ширину подчеркивания под табами не зависимой от ширины таба, в половину ширины экрана
> issue-#408 - Ширина подчеркивания под табами

- src/reducers/modal.reducer.js
> Issue #262

- src/blocks/create-empty/header/create-empty-header.js
- src/reducers/collection.reducer.js
- src/utils/shared-functions.js
Сделал очистку стейта при возврате из добавления коллекции.
close #473 
close #416
> Вынес функции из редюссера к вспомогательным.

- src/blocks/onboarding/onboarding.js
> Удалил кнопку 'Назад' на первой странице 'Onboarding'

- package.json
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/context-menu/__item/context-menu__item.js
- src/blocks/create-description/header/create-description-header.scss
- src/blocks/create-link-comment/__header/create-link-comment__header.js
- src/blocks/create-link-comment/__header/create-link-comment__header.scss
- src/blocks/create-link-comment/create-link-comment.js
- src/blocks/create-link-comment/create-link-comment.scss
- src/blocks/create-link-comment/index.js
- src/blocks/create-link/create-link.js
- src/blocks/create-link/header/create-link-header.js
- src/blocks/create-link/header/create-link-header.scss
- src/blocks/create-link/load/create-link-load.js
- src/blocks/index.js
> Issue #407

- src/blocks/card-footer/card-footer.js
- src/blocks/create-card/create-card.js
- src/blocks/create-card/create-card.scss
- src/blocks/create-empty/header/create-empty-header.js
Сделал градиент на добавление коллекции.
Поправил отображение хэштегов.
Порефакторил и избавился от части работы с локальным стейтом в добавлении коллекции.
> Issue #404 Доработки в создании коллекции

- src/blocks/account-profile/header/account-profile-header.js
> Контекстное меню на выход из профиля

- src/blocks/create-link/load/create-link-load.js
- src/blocks/link-card/link-card.js
> Не открывать ссылку при создании пр клике на карточку

- src/blocks/create-description/header/create-description-header.js
- src/blocks/create-description/header/create-description-header.scss
> Issue #500

- src/blocks/creating-successfully/creating-successfully.js
> Плагин социального шэринга не открывается сам на окне готово

- src/reducers/user.reducer.js
- src/tests/reducers/search.test.js
- src/tests/reducers/user.test.js
> Issue #512

- package-lock.json
- package.json
- src/reducers/authorization.reducer.js
- src/tests/reducers/authorization.test.js
> Странные тесты какие-то для авторизации

- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/create-link/header/create-link-header.scss
> Бажок поправила с цветом

- src/reducers/another-user.reducer.js
- src/tests/reducers/another-user.test.js
> Тесты для reducer another-user

- src/blocks/authorization/authorization.js
- src/blocks/button/button.js
- src/blocks/button/button.scss
- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/create-empty-card/create-empty-card.js
- src/blocks/create-link/load/create-link-load.js
- src/blocks/creating-successfully/creating-successfully.js
- src/blocks/modal-error/modal-error.js
- src/variables.scss
> Issue #219 - Убрал заинлайнненные стили из компонента 'Button'

- src/blocks/creating-successfully/creating-successfully.js
- src/blocks/creating-successfully/header/creating-successfully-header.js
> issue-#528 Переход в профиль после создания любой подборки

- src/reducers/create-collection.reducer.js
- src/tests/reducers/create-collection.test.js
> Тесты для create-collection

- src/blocks/user-info/user-info.js
- src/blocks/user-info/user-info.scss
> Убрал неиспользуемый user-description из информации о пользователе

- src/blocks/hash-tag/hash-tag.js
- src/blocks/onboarding/onboarding.js
- src/reducers/onboarding.reducer.js
> Поправила баг с выбором тегов на онбоардинге

- src/blocks/toggle-text/toggle-text.scss
> Поправила баг с разворотом текста на iOS ниже 9.3

- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/collection-detail/info/collection-detail-info.scss
> Отображаю 'замочек' закрытой подборки в детально

- src/blocks/account-profile/feed-item/account-profile-feed-item.js
- src/blocks/account-profile/feed-item/account-profile-feed-item.scss
> Отображаю 'Замочек' закрытой подборки в профиле

- .travis.yml
> Конфиг для Трависа

- src/reducers/onboarding.reducer.js
- src/services/onboarding.service.js
> Отдельный запрос на отправку тегов после онборадинга, чтобы вес больше проставлялся

- src/blocks/account-profile/account-profile.scss
- src/blocks/card-footer/card-footer.js
- src/blocks/collection-card/collection-card.js
- src/blocks/collection-detail/info/collection-detail-info.js
- src/blocks/hash-tag/hash-tag.scss
- src/blocks/user-info/user-info.scss
- src/services/collection.service.js
> Переписала немного сохранение подборок и стили поправила чуток

- src/blocks/collection-detail/__header/collection-detail__header.js
- src/blocks/collection-detail/__header/collection-detail__header.scss
- src/blocks/collection-detail/collection-detail.js
- src/blocks/collection-detail/info/collection-detail-info.js
> Header в collection-detail в элемент переделала

- src/config.js
- src/services/another-user.service.js
- src/services/authorization.service.js
- src/services/bookmarks.service.js
- src/services/collection.service.js
- src/services/create-collection.service.js
- src/services/feed.service.js
- src/services/link.service.js
- src/services/onboarding.service.js
- src/services/personal-tags.service.js
- src/services/search.service.js
- src/services/user.service.js
- src/utils/shared-functions.js
> Конструктор запросов на сервер.

- src/reducers/loader.reducer.js
- src/reducers/onboarding.reducer.js
- src/tests/reducers/loader.test.js
- src/tests/reducers/onboarding.test.js
> Issue #565

- src/blocks/user-profile/__feed-item/user-profile__feed-item.js
- src/blocks/user-profile/__feed-item/user-profile__feed-item.scss
- src/blocks/user-profile/__feed/user-profile__feed.js
- src/blocks/user-profile/__feed/user-profile__feed.scss
- src/blocks/user-profile/__header/user-profile__header.js
- src/blocks/user-profile/__header/user-profile__header.scss
- src/blocks/user-profile/user-profile.js
- src/blocks/user-profile/user-profile.scss
> Рефакторинг user-profile

- src/blocks/avatar/avatar.js
- src/blocks/avatar/avatar.scss
> Рефакторинг компонента avatar

- src/blocks/home-top-bar/home-top-bar.js
- src/services/authorization.service.js
- src/utils/shared-functions.js
> Поправила баг с аватаркой пользователя на домашней странице

- src/reducers/create-collection.reducer.js
> Поправил багу с добавлением коллекции - не появлялось окно об успешном создании

- src/blocks/link-preview/__footer/link-preview__footer.js
- src/blocks/link-preview/__footer/link-preview__footer.scss
- src/blocks/link-preview/__header/link-preview__header.js
- src/blocks/link-preview/__header/link-preview__header.scss
- src/blocks/link-preview/link-preview.js
> Issue #592 - рефаткоринг компонента 'LinkPreview'

- src/blocks/search/__result/search__result.js
> Текст поправила в поисковой выдаче и кнопку убрала

- src/blocks/collection-detail/collection-detail.js
- src/blocks/toggle-text/toggle-text.js
- src/reducers/collection.reducer.js
> Поправила баг в toggle-text

- src/blocks/my-profile/__header/my-profile__header.scss
> Поправил контекстное меню в профиле - теперь оно идет поверх аватара
